FLASHSCORE_PREMIER_LEAGUE_MAP_NAME = {
    'Manchester City': None, 
    'Liverpool': None, 
    'Chelsea': None, 
    'Tottenham': None, 
    'Manchester Utd': None, 
    'Arsenal': None, 
    'West Ham': None, 
    'Wolves': None, 
    'Leicester': None, 
    'Brighton': None, 
    'Brentford': None, 
    'Southampton': None, 
    'Crystal Palace': None, 
    'Newcastle': None, 
    'Aston Villa': None, 
    'Leeds': None, 
    'Everton': None, 
    'Burnley': None, 
    'Watford': None, 
    'Norwich': None
}

FLASHSCORE_BUNDESLIGA_MAP_NAME = {
    'Bayern Munich': None,
    'Dortmund': 'B. Dortmund',
    'RB Leipzig': None,
    'Bayer Leverkusen': None,
    'Freiburg': None,
    'Union Berlin': None,
    'FC Koln': None,
    'Hoffenheim': None,
    'Mainz': None,
    'Eintracht Frankfurt': 'Eintracht',
    'B. Monchengladbach': None,
    'Bochum': None,
    'Wolfsburg': None,
    'Augsburg': None,
    'Hertha Berlin': None,
    'Stuttgart': None,
    'Arminia Bielefeld': None,
    'Greuther Furth': None
}

FLASHSCORE_LALIGA_MAP_NAME = {
    'Real Madrid': None,
    'Barcelona': None,
    'Sevilla': None,
    'Atl. Madrid': None,
    'Betis': None,
    'Real Sociedad': None,
    'Villareal': None,
    'Ath Bilbao': None,
    'Osasuna': None,
    'Valencia': None,
    'Celta Vigo': None,
    'Espanyol': None,
    'Elche': None,
    'Rayo Vallecano': None,
    'Getafe': None,
    'Cadiz CF': None,
    'Granada CF': None,
    'Mallorca': None,
    'Levante': None,
    'Alaves': None
}

FLASHSCORE_EKSTRAKLASA_MAP_NAME = {
    'Lech Poznan': None,
    'Pogon Szczecin': None,
    'Rakow': None,
    'Lechia Gdansk': None,
    'Piast Gliwice': None,
    'Radomiak Radom': None,
    'Wisla Plock': None,
    'Cracovia': None,
    'Gornik Z.': 'Gornik Zabrze',
    'Legia': 'Legia Warszawa',
    'Warta Poznan': None,
    'Jagiellonia': None,
    'Stal Mielec': None,
    'Slask Wroclaw': None,
    'Zaglebie': 'Zaglebie Lubin',
    'Wisla': 'Wisla Krakow',
    'Leczna': 'Gornik Leczna',
    'Termalica B-B.': None
}

FLASHSCORE_PIERWSZA_LIGA_MAP_NAME = {
    'Legnica': 'Miedz Legnica',
    'Widzew Lodz': None,
    'Arka Gdynia': None,
    'Korona Kielce': None,
    'Chrobry Glogow': None,
    'LKS Lodz': None,
    'Sandecja Nowy S.': 'Sandecja',
    'Odra Opole': None,
    'Podbeskidzie': None,
    'Tychy': 'GKS Tychy',
    'R. Rzeszow': 'Resovia',
    'Skra': None,
    'Zaglebie Sosnowiec': None,
    'GKS Katowice': None,
    'Puszcza': None,
    'Stomil Olsztyn': None,
    'Polkowice': 'Gornik Polkowice',
    'GKS Jastrzebie': None
}

FLASHSCORE_VEIKKAUSLIIGA_MAP_NAME = {
    'KuPS': None,
    'HJK': None,
    'Haka': None,
    'VPS': None,
    'Honka': None,
    'Lahti': None,
    'Mariehamn': None,
    'Inter Turku': None,
    'SJK': None,
    'AC Oulu': None,
    'Ilves': None,
    'HIFK': None
}